services:
  soaauth:
    image: soaauth
    ports:
      - "8080:8080"
    environment:
      ADDRESS: "127.0.0.1:8080"
      CLIENT_ID:
      CLIENT_SECRET:
      DATA_DIR: "/opt/data/users"
      OAUTH2_URI: "http://play.storyofalicia.com/callback"
      FORWARD_URI: "https://storyofalicia.com"